### ISSUE TITLE
Open-sourcing the TaoDescribe dataset

### ISSUE THREAD

**Issue by Remaining** [THUcqb/KOBE#1]

**Comment by qibinc** [comment]
Hi @Remaining ,

论文中使用的数据集 **TaoDescribe** 的开放，我们两个月前已开始积极推进，但由于 Alibaba 内部需要进行一系列必经流程（脱敏、数据披露，whatever），还需等待一段时间。

对您的项目进展造成的影响我们深表歉意！！同时，希望您可以继续关注此仓库，如果有数据集、代码方面的发布/更新，我们都会第一时间放在这个仓库中。

**Comment by Remaining** [comment]
非常感谢您的回复。我是一名大四的学生，准备读博士。对广告个性化生成非常感兴趣，所以对您的论文认真研读并且想复现一下。这篇论文脉络非常清晰，给了我很大的启发，让我感觉到您论文思路的专业性。再次感谢您。并且对您愿意公开数据集表示感谢。------------------ 原始邮件 ------------------
发件人: "Qibin Chen"<notifications@github.com>
发送时间: 2019年5月5日(星期天) 中午12:04
收件人: "qibinc/KOBE"<KOBE@noreply.github.com>;
抄送: "Remaining"<1975642935@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [qibinc/KOBE] 请问您《Towards Knowledge-Based Personalized Product Description Generation in E-commerce》这篇论文的TaoDescribe的数据集可以公开么~ (#1)



Hi @Remaining ,
 
论文中使用的数据集 TaoDescribe 的开放，我们两个月前已开始积极推进，但由于 Alibaba 内部需要进行一系列必经流程（脱敏、数据披露，whatever），还需等待一段时间。
 
对您的项目进展造成的影响我们深表歉意！！同时，希望您可以继续关注此仓库，如果有数据集、代码方面的发布/更新，我们都会第一时间放在这个仓库中。
 
&mdash;
