### ISSUE TITLE
Reversed word order in target compared to input

### ISSUE THREAD

**Issue by jiqiujia** [THUcqb/KOBE#12]
I trained a baseline model using my own data and I found an interesting result. Different from your baseline setting, I use word-based encoding and char-based decoding. It seems that the model tends to generate words according to the input but in reversed order.
![image](https://user-images.githubusercontent.com/8109984/61216047-07f84480-a73f-11e9-83a1-b1aaa554cc7c.png)
![image](https://user-images.githubusercontent.com/8109984/61216297-87861380-a73f-11e9-9854-e87432eea15e.png)

Could you explain this phenomenon? I also wonder if word-based encoding and char-based decoding leads to some information interpretation gap between encoder and decoder?

**Comment by qibinc** [comment]
Hi @jiqiujia ,

I'm not sure what exactly caused this problem but you may want to check here:

https://github.com/THUDM/KOBE/blob/43ebc51206019b9375f0372813aa1d68eaca6581/core/utils/data_helper.py#L118

In the padding function, we reverse the source sequence. This is empirically added for seq2seq with uni-directional RNNs. Transformers actually don't require this (the result should be the same) but this might be the cause of the problem. **Make sure this function is called consistently during training, testing and generation.**

Hope this helps! BTW, I personally don't think word-based encoding and char-based decoding caused this problem. Although in our paper we used char-based encoding, the encoder and the decoder didn't share the vocabulary (i.e., input embedding) either.

**Comment by jiqiujia** [comment]
That's it! Thank you~
