### ISSUE TITLE
User Categories as an attribute

### ISSUE THREAD

**Issue by Flitternie** [THUcqb/KOBE#14]
What are the real tags (string format) corresponding to the user category attributes (int format) in the src.str files? 

P.S.
Great works! Really appreciate your efforts in open sourcing the datasets.

**Comment by qibinc** [comment]
Hi @Flitternie ,

Thanks for being interested in this work! This might be what you need:

```json
{
    "时尚靓妹": 0,
    "家庭主妇": 1,
    "烹饪达人": 2,
    "买鞋控": 3,
    "数码达人": 4,
    "吃货": 5,
    "爱包人": 6,
    "高富帅": 7,
    "花卉一族": 8,
    "职场办公": 9,
    "运动一族": 10,
    "有型潮男": 11,
    "爱听音乐": 12,
    "收纳达人": 13,
    "酒品人生": 14,
    "养生专家": 15,
    "美丽教主": 16,
    "追风骑士": 17,
    "户外一族": 18,
    "速食客": 19,
    "乐器迷": 20,
    "阅读者": 21,
    "动漫迷": 22,
    "网络一族": 23,
    "收藏家": 24,
    "健美一族": 25,
    "游戏人生": 26,
    "休闲大咖": 27,
    "情趣一族": 28,
    "白富美": 29,
    "学霸": 30,
    "摄影一族": 31,
    "旅行者": 32,
    "绘画家": 33,
    "舞林人士": 34,
}
```

In addition, you can explore the user category dataset further in [this file](https://www.dropbox.com/sh/nnnq9eobmn6u44v/AABnWQzig7W_MKg0u7xfL0Qsa/content_tag_dataset.zip?dl=1), which includes more detailed user category information.

Best,
Qibin

**Comment by Flitternie** [comment]
Thanks for the reply. That's really helpful. 
Still hv one question: 
Does a>, b>,  c> in src.str files stand for appearance, texture, function aspects respectively? 

Regards,
Flitter

**Comment by qibinc** [comment]
Yes! You're right.

**Comment by Flitternie** [comment]
Thanks for your timely reply!

Regards,
Flitter
