### ISSUE TITLE
Question about BiAttention 

### ISSUE THREAD

**Issue by AbnerCode** [THUcqb/KOBE#15]
Hi, Qibin

First, thanks to your open source codes.

I have some questions about your code.
1. I want to know the baseline model in your weather using two transformer encoders? 
2. In your code, the BiAttention is used, `self.condition_context_attn = BiAttention(config.hidden_size, config.dropout)`. But the self.condition_context_attn is not be used. So I wanna get the detail setting.

Best Wishes!

**Comment by qibinc** [comment]
Hi @AbnerCode ,

Thanks a lot for being interested in this work and checking out the code!

#### Question 1
No, we use the second encoder to encode retrieved knowledge. As the baseline model doesn't incorporate external knowledge, there is only one encoder – title encoder.

#### Question 2
For KOBE, `condition_context_attn` is not used in `transformer.py`, but used in `tensor2tensor.py`. Make sure you have the latest code. See:

https://github.com/THUDM/KOBE/blob/6f06ec53998800d4f7260191314be99faf3b8696/core/models/tensor2tensor.py#L298

**Comment by AbnerCode** [comment]
Hi @qibinc ,

It is such an honor to hear from you.
![image](https://user-images.githubusercontent.com/35194862/62851728-aa452100-bd19-11e9-937f-040fe0c1af13.png)
So, as you say, you only use the title encoder as your baseline, which does not use the BiAttention. Is it like this?

**Comment by qibinc** [comment]
Hi @AbnerCode ,

The above figure displays the architecture of KOBE.

For baseline, which is without the knowledge encoder, looks like this:

![image](https://user-images.githubusercontent.com/22570685/62853123-f2fed900-bd1d-11e9-8b07-1f6c33046834.png)

Best,
Qibin Chen

**Comment by AbnerCode** [comment]
Hi @qibinc ,

Thanks for your reply! 
 In addition, I wanna know why you use the 2 layer transformer as the decoder. Generally,  the layer is set as 6. 

Best wishes!

**Comment by qibinc** [comment]
Hi @AbnerCode ,

> In addition, I wanna know why you use the 2 layer transformer as the decoder. Generally, the layer is set as 6.

Please check out https://github.com/THUDM/KOBE/issues/13. It mentions the same problem.

**Comment by AbnerCode** [comment]
Hi @qibinc ,

Thanks!

Best Wishes
