### ISSUE TITLE
Question about allWeight and eval_  in beam sample

### ISSUE THREAD

**Issue by AbnerCode** [THUcqb/KOBE#17]
Hi @qibinc 

Thanks for your patience. I found that your beam sample including a parameter eval_. But it is likely useful for your training or I am wrong?

Best wishes,

**Comment by qibinc** [comment]
Hi @AbnerCode ,

It's just for debugging and visualization. It has no effect on the training. You can ignore these.

Best, 
Qibin

**Comment by AbnerCode** [comment]
Hi @qibinc ,

Thanks for your reply, I will continue to reproduce your paper.

Best wishes,

**Comment by qibinc** [comment]
Hi @AbnerCode ,

Thank you for your patience! I noticed that you have spent several days in studying the code. I apologize for the code quality and lack of code comments if they've caused inconvenience to you. And currently I don't have sufficient time to refactor and beautify the code. If you encounter more problems, feel free to raise new issues!

Best,
Qibin
