### ISSUE TITLE
Question about using rouge to evaluate the model

### ISSUE THREAD

**Issue by AbnerCode** [THUcqb/KOBE#18]
Hi @qibinc 

I am using rouge to evaluate the score. I change the metrics: ['bleu'] to metrics: ['rouge'], but it seems can not useful? Are there other things I need to do? 

Best wishes,

**Comment by qibinc** [comment]
We don't support ROUGH for evaluation, though we have relevant code in `metrics.py`. You should modify the `rough` function in `metrics.py` if you want to use rough score. If you can't solve the problems by yourself, please post detailed errors here so we can discuss together.

**Comment by AbnerCode** [comment]
Thanks for you! 
I will modify the metrics.py as soon as possible!
