### ISSUE TITLE
Question about padding 

### ISSUE THREAD

**Issue by AbnerCode** [THUcqb/KOBE#19]
Hi @qibinc 

I found that you reverse the src, can you give some reasons about this? 
![image](https://user-images.githubusercontent.com/35194862/63248719-8b570980-c29a-11e9-8905-0ea093046b66.png)

Best wishes,

**Comment by qibinc** [comment]
Hi @AbnerCode ,

Please see https://github.com/THUDM/KOBE/issues/12#issuecomment-511406752

Hope this helps :)

**Comment by AbnerCode** [comment]
Hi @qibinc 
Thanks for your help!

Best wishes
