### ISSUE TITLE
Implementation of BIDAF to combine knowledge encoding and title representation

### ISSUE THREAD

**Issue by kiminh** [THUcqb/KOBE#2]
Hi,would please figure out where is the implementation of BIDAF to combine knowledge encoding and title representation in this released code? Thanks a lot.

**Comment by qibinc** [comment]
Hi @kiminh ,

Thanks for your attention on this work!

I apologize that we're still working on dataset and refactoring code and thus not ready for a clean release now.

For your request, I just uploaded the `supporting-fact` branch, which includes the BiDAF and knowledge relevant code. You can check it out here:

https://github.com/qibinc/KOBE/blob/c957faeb777abdad7cd2ef4d3d3a4edbf514b73a/SeqGen_Shuangqing/models/transformer.py#L97

and 

https://github.com/qibinc/KOBE/blob/c957faeb777abdad7cd2ef4d3d3a4edbf514b73a/SeqGen_Shuangqing/models/tensor2tensor.py#L210

The code might be dirty and I don't encourage you to stuck on it for too long (really sorry about that.. expect a clean release at the end of this month) but it basically contains all the stuffs that make things work like the paper.

Best,
Qibin Chen

**Comment by kiminh** [comment]
Thanks for your quick reply and your suggestion.
