### ISSUE TITLE
preprocess.py数据预处理时一些困惑

### ISSUE THREAD

**Issue by mattzheng** [THUcqb/KOBE#25]
感谢作者的开源~  `aspect_user.yaml`训练成功，本想用训练好的模型，用自己的数据试一下，好像一直没跑通，卡在`makeVocabulary`/`makeData`。
通过天池下载了的`TaoDescribe `数据集是源数据集；通过`download_preprocessed_tao.py`下载的是预处理的。
源数据集 -> 预处理数据过程中，在`preprocess.py`文件中：
其中，`In src files, <x> <y> means this product is intended to show with aspect <x> and user category <y>`中， `aspect <x>`这个定义没给出？

**Comment by mattzheng** [comment]
> 感谢作者的开源~ `aspect_user.yaml`训练成功，本想用训练好的模型，用自己的数据试一下，好像一直没跑通，卡在`makeVocabulary`/`makeData`。
> 通过天池下载了的`TaoDescribe `数据集是源数据集；通过`download_preprocessed_tao.py`下载的是预处理的。
> 源数据集 -> 预处理数据过程中，在`preprocess.py`文件中：
> 其中，`In src files, <x> <y> means this product is intended to show with aspect <x> and user category <y>`中， `aspect <x>`这个定义没给出？

自问自答一下。。在api.py中有`DescriptionGenerator`，稍微修改一下.yaml 和 DescriptionGenerator函数就可以预测了。。

**Comment by yuulin** [comment]
api.py具体怎么修改呢？

**Comment by qibinc** [comment]
Hi @yuulin 关于 <x> <y> 的定义，请参见 https://github.com/THUDM/KOBE/issues/14 

在 `api.py` 中把用到这些tag的部分，换成您自己的tag就可以了～
