### ISSUE TITLE
user's implicit feedback data

### ISSUE THREAD

**Issue by johnnyjana730** [THUcqb/KOBE#26]
Thanks for the code and paper.
I am curious about the soft assignment of user categories. Is it possible to provide the implicit feedback data (click, dwell time) to the public?

**Comment by qibinc** [comment]
Hi @johnnyjana730 ,

Unfortunately we didn't directly use these data (click, dwell time) in this project and couldn't release them to the public at this time. However, we have released soft assignment data here https://www.dropbox.com/sh/nnnq9eobmn6u44v/AAA7s4YkVbslS-6slDIOn4MYa?preview=content_tag_dataset.zip, as described in README (the un-preprocessed data part) and you can use it directly. 

Hope this helps!
