### ISSUE TITLE
Question about personalized generation result

### ISSUE THREAD

**Issue by johnnyjana730** [THUcqb/KOBE#27]
I train your model with the default parameter. Is it the result same as you? I can't tell there is an obvious difference from the sentence (for me) with different item aspects and user categories. Can the author provide your result (best_bleu_prediction.txt) after training? Thanks!

Here is mine best_bleu_prediction.txt after training  (no adapting beam searching). 

![image](https://user-images.githubusercontent.com/20666568/74602188-1f3a4e80-50e1-11ea-85e3-5c85264a5945.png)
[best_bleu_prediction.txt](https://github.com/THUDM/KOBE/files/4209583/best_bleu_prediction.txt)

**Comment by qibinc** [comment]
Hi @johnnyjana730 ,

Thanks for being interested in this work. I believe there is a difference in the outputs. For example:

![image](https://user-images.githubusercontent.com/22570685/74705259-3c406000-524e-11ea-9055-332bb83c437f.png)

Both sentences mentioned the functions first. However, apparently the first sentence focuses on the "appearance" later. ”浮雕工艺“，”精致的做工“，”美观大方“, while the second sentence is still focusing on things like materials, safety and health. 

This observation is actually very close to what we observed in the paper, e.g., Figure 1. And I'm sure there are many similar examples. 

However, one annoying thing, as you must have observed, is the repetitive terms, which makes the outputs look unintelligent. To alleviate this, we have implemented repetitive term blocking and you have to enable beam search to use it. It will be easier to identify the effects with better outputs.

Hope this helps!

**Comment by johnnyjana730** [comment]
Thanks for your reply.  I am afraid that I get different result from you
