### ISSUE TITLE
關於Title input的問題

### ISSUE THREAD

**Issue by ga2006084851** [THUcqb/KOBE#28]
作者您好，謝謝您的分享，我想請問一下，
問題一:
關於Title x 的作法，請問是把"(10)(a)牛仔外套女2019春秋装新款宽松学生韩版bf原宿风外套牛仔衣潮"這個當成x轉成embedding並與(10)(a)這個attribute的embedding做相加丟入encoder，
還是純粹把"牛仔外套女2019春秋装新款宽松学生韩版bf原宿风外套牛仔衣潮"當成x,
並與(10)(a)這個attribute的embedding做相加丟入呢?
問題二:
關於最後生成的personalized product description，生成的字數個數是隨機的嗎?
有辦法指定限制字數嗎? 還是這是根據訓練集的description長度來決定的呢?

**Comment by qibinc** [comment]
Hi @ga2006084851 ,

1. The latter. 
2. 在我们的这篇工作和 code 中没有办法限制 decode 出来的字数，不过基本也都跟训练集的 description 长度差不多。可以在 beam search decode 的时候强行在某个 timestep 取 <eos> (end of sequence)，但会影响效果。我觉得应该有一些文献尝试解决过这个问题，但效果应该有限，毕竟不能和训练集中的长度相差太多。如果训练集中大都是 100，而你需要 30，这样可以考虑用其他数据训练一个 summarization 的模型，对生成的过长的 description 做后处理。或者如果原来的训练数据充足，建议直接丢掉过长的 training sample.

Hope this helps!

**Comment by ga2006084851** [comment]
我明白了，真的感謝您的幫忙!!!
