### ISSUE TITLE
Where is the dataset?

### ISSUE THREAD

**Issue by ZephyrChenzf** [THUcqb/KOBE#3]
Where is the dataset?

**Comment by qibinc** [comment]
Hi @ChenZhongFu ,

Thanks for your attention on this work!!

I apologize that we're still working on dataset and refactoring code and thus not ready for a clean release now.

Really sorry about that.. As said in README, you could expect a formal release at the end of this month. (i.e., in a few days)

Best,
Qibin Chen

**Comment by ZephyrChenzf** [comment]
> Hi @ChenZhongFu ,
> 
> Thanks for your attention on this work!!
> 
> I apologize that we're still working on dataset and refactoring code and thus not ready for a clean release now.
> 
> Really sorry about that.. As said in README, you could expect a formal release at the end of this month. (i.e., in a few days)
> 
> Best,
> Qibin Chen

Thank you very much for your reply. I look forward to the completion of your code. Best wishes.

**Comment by qibinc** [comment]
Hi @ChenZhongFu ,

Both the original dataset and the preprocessed dataset is available now. Please checkout the new README~

Best,
Qibin
