### ISSUE TITLE
Can you please help me with this cuda assertion error 

### ISSUE THREAD

**Issue by sgoyal28** [THUcqb/KOBE#30]
File "core/train.py", line 327, in <module>
    device, devices_id = misc_utils.set_cuda(config)
  File "/home/shreya/KOBE/core/utils/misc_utils.py", line 19, in set_cuda
    assert config.use_cuda == use_cuda
AssertionError

**Comment by qibinc** [comment]
Hi @goyal2891 ,

Please install torch with CUDA support (print(torch.cuda.is_available()) shows True). Hope this helps!
