### ISSUE TITLE
请问怎么对训练好的模型进行测试

### ISSUE THREAD

**Issue by 958143741** [THUcqb/KOBE#31]
请问怎么对训练好的模型进行测试

**Comment by qibinc** [comment]
Hi @958143741 ,

用训练好的模型 beam search 进行生成，请参考

https://github.com/THUDM/KOBE#generation

1. BLEU score 在 training/generation 过程中生成的 tensorboard 里。
2. diversity score 可以通过 `python scripts/score_diversity.py experiments/xxx/best_bleu_prediction.txt` 得到

**Comment by 958143741** [comment]
我用代码里的测试集跑可以跑通生成描述，为什么用自己爬取的数据集并转换而成的id就出错了（因为没有标签，所以我叫标签也用标题输入），，有个进度条跑到2%就出错了

**Comment by qibinc** [comment]
@958143741 

Hi,

请告知一下具体的错误信息，我们可以一起看看是哪里的问题

**Comment by 958143741** [comment]
谢谢回答
      问题我已经解决了，我将/KOBE-master/core/dataset.py中的 data['test']['length']=输入标题的数目，而不是固定的5236条，问题就解决了

**Comment by jiangliqin** [comment]
请问训练模型在什么GPU环境花了多久？

**Comment by qibinc** [comment]
Hi @jiangliqin , 我们当时在一台8卡V100的机器上用了3天跑了paper上的全部最终实验（详细配置见 Appendix A.1 的 Hardware Configuration 段落）。如果只跑单个实验，预计需要单卡的12～24小时，取决于显卡～
