### ISSUE TITLE
How to build Data.pkl?

### ISSUE THREAD

**Issue by liweitj47** [THUcqb/KOBE#32]
Thank you for sharing such a wonderful project. I find the code very inspiring. However, during viewing the code, I could not find the script to build "data.pkl" and therefore can hardly infer the format of the data. Can you please upload the corresponding code or provide the data format in data.pkl? Thank you again.

**Comment by qibinc** [comment]
Hi @liweitj47 ,

Sorry for the late reply. Just in case others are still interested in this. `data.pkl` is built by `core/preprocess.py`.
