### ISSUE TITLE
Explaination about your preprocessed data

### ISSUE THREAD

**Issue by huniu20** [THUcqb/KOBE#38]
![image](https://user-images.githubusercontent.com/70004880/123625142-05b32600-d842-11eb-983e-a41a9a395fca.png)
Could you please explain the accurate meaning of these various filenames?

**Comment by ssexuejinwei** [comment]
'src' files : each column represents a data (user catagory[24], product aspect[3]), the product title
'tgt' files : represent the detail description for each product.
for these files,'str' means the origin string, 'id' means the index of the word in dict files.
'supproting_facts' files: means the knowledge

**Comment by qibinc** [comment]
Thanks for clarifying this! The above explanation is totally correct. Meanwhile, this post describes the meaning of the user category id https://github.com/THUDM/KOBE/issues/14#issuecomment-516262659 . Hope this helps

**Comment by qibinc** [comment]
Hi @huniu20 ,

We have rewritten this codebase with latest versions of DL frameworks and significantly improved the installation, code quality, reproducibility and visualization. The data preprocessing part is also much clearer and you can find the explanations of the data files in the README now.

Here is a screenshot of the KOBE-v2's training progress, in case your are still interested:

![image](https://user-images.githubusercontent.com/22570685/147371197-88b05025-3ae6-4f00-ab9e-918a55ea2a6e.png)

Best,
