### ISSUE TITLE
At the end of the run, the bleu score can no longer be improved at around 6.

### ISSUE THREAD

**Issue by cooclzw** [THUcqb/KOBE#41]
How can I use the data set in the example to train with baseline to achieve the total number of 81 in the paper

**Comment by qibinc** [comment]
Hi @cooclzw ,

Thanks for your interest in this work. Could you please provide more context about your training environment, process, and results? Feel free to paste any env settings (e.g., torch version), training logs, tensorboard screenshots, etc.

Besides, could you provide be a little more specific and point to the table where the number `81` is in the paper?

Best,

**Comment by cooclzw** [comment]
![A62C34F5-ACA4-41DF-9BD3-5F3AA9B55826](https://user-images.githubusercontent.com/68526391/133870587-9fa829fb-b50e-4dba-b92c-1794f96db881.png
![image](https://user-images.githubusercontent.com/68526391/133870593-e786fe7a-126c-4468-865d-49c6d16522de.png)
)
centos8 +python3.7+torch 1.4

**Comment by cooclzw** [comment]
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/68526391/133870664-247d01ca-1f57-41c7-8357-f3b99376a7ed.png">
python core/train.py --config configs/aspect_user_knowledge.yaml --expname aspect-user-knowledge

**Comment by qibinc** [comment]
hi @cooclzw ,

This is similar to what we observed during training. To reproduce the number in the paper (bleu=7.6 for this experiment, please run beam search with the saved checkpoint. Refer to https://github.com/THUDM/KOBE#generation

**Comment by qibinc** [comment]
Hi @cooclzw ,

We have rewritten this codebase with latest versions of DL frameworks and significantly improved the installation, code quality, reproducibility and visualization. Here is a screenshot of the KOBE-v2's training progress, in case your are still interested:

![image](https://user-images.githubusercontent.com/22570685/147371167-e87e9baf-417d-4d9c-9dff-7491e396e634.png)

Best,
