### ISSUE TITLE
Is there any dataset in English?

### ISSUE THREAD

**Issue by batprem** [THUcqb/KOBE#42]
Hello, your model is very interesting, but I don't have any knowledge of Chinese as the model outputs. So, I'd to ask you about is there any dataset in English available?

**Comment by qibinc** [comment]
Hi @batprem, thanks for your attention. Sorry that for all I know I'm not aware of a similar English dataset. This work was done at Alibaba where the products on taobao.com are all in Chinese. I suggest that you look for similar works coming out from Amazon.
