### ISSUE TITLE
inference

### ISSUE THREAD

**Issue by AItechnology** [THUcqb/KOBE#47]
貌似最新的readme没有generation和api部分？该怎么做测试呢？

**Comment by qibinc** [comment]
https://github.com/THUDM/KOBE#evaluating-kobe

**Comment by qibinc** [comment]
生成结果的例子和分数可以在wandb dashboard上看到。如果需要所有生成结果，可以修改 https://github.com/THUDM/KOBE/blob/ad4957cf701cd42243be9ae222ed6f92de58a97e/kobe/models/model.py#L101 的代码把evaluation 结果存下来。
我们暂时没有提供interactive的api。希望以上有所帮助，谢谢
