### ISSUE TITLE
Difference between tensor2tensor.py and seq2seq.py

### ISSUE THREAD

**Issue by yqNLP** [THUcqb/KOBE#6]

**Comment by qibinc** [comment]
Hi @yezqNLP ,

Thanks for your interest in this work!

In `tensor2tensor.py`, the model used is Transformer while in `seq2seq.py` the model used is RNN (e.g., LSTM, GRU)

Hope this helps.

Best,
Qibin Chen

**Comment by yqNLP** [comment]
thanks
