### ISSUE TITLE
code error?

### ISSUE THREAD

**Issue by xiaolingzang** [THUcqb/KOBE#7]
when you do knowledge encoding,  the code use tgt_vocab for knowledge and change 
src_vocab_size , but after that the code change back config.src_vocab_size = config.src_vocab_size,there may be a error

**Comment by qibinc** [comment]
Hi @xiaolingzang ,

Thanks for your interest in this work!

You're right! This line should be `config.src_vocab_size = src_vocab_size` to set it back. Luckily, this doesn't affect anything.. The argument `config.src_vocab_size` is used in the encoder for `x`, which is defined before these lines. But still, I'm really grateful that you point this out. I'll fix this in the next update.

Much thanks!

Best
Qibin Chen

**Comment by qibinc** [comment]
Fixed
