### ISSUE TITLE
train by multi-gpu

### ISSUE THREAD

**Issue by wadefk** [THUcqb/KOBE#8]
How to train the model by multi-gpu

**Comment by qibinc** [comment]
Hi @wadefk ,

Thanks for your interest in this work!

We currently don't support training on multiple GPUs. Really sorry about that. The only way to utilize multiple GPUs is to train multiple models with different hyperparaters, one on each GPU.

Best,
Qibin Chen

**Comment by wadefk** [comment]
thanks
